#!/bin/bash --login
# This file was automatically generated by jinjaroot. Do not edit directly. See the .jinjaroot dir.

set -e

echo "activating conda environment..."

# activate conda environment and let the following process take over
conda activate myenv
conda list
exec "$@"