apiVersion: v1
kind: Service
metadata:
    name: labbox-ephys-ephys1-service
spec:
    selector:
        app: labbox-ephys-ephys1
    ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 15310
    - name: websocket
      protocol: TCP
      port: 15308
      targetPort: 15308
    - name: api-http
      protocol: TCP
      port: 15309
      targetPort: 15309
    - name: kacherynode
      protocol: TCP
      port: 14207
      targetPort: 14207
    - name: kacherynode-websocket
      protocol: TCP
      port: 14208
      targetPort: 14208
    type: LoadBalancer
